### ISSUE TITLE
Change (color)view arguments?

### ISSUE THREAD

**Issue by jvanlunenburg** [JuliaImages/ImageCore.jl#132]
I think `colorview(A, C)` would facilitate piping if there is a set default parameter.
E.g. let's say C has a sensible default type based on `size(channelview(A),1)`, we could then do:
```
img = load("mandrill") |> channelview |> modifyelements |> colorview
```  
As I understand the pipe operator in base Julia needs single argument functions, and all views will always need an image, but parameters (if any) may be optional. So it makes sense to make `A` the first argument for all views. Is there a reason for the apparent convention: 
```viewfunction(parameter, image, other_parameters)```?

**Comment by timholy** [comment]
I'm a bit reluctant to have "sensible defaults" based on array sizes. If someone snips out a 3x3x3 block of a 3d grayscale image and then passes it through a pipeline that includes colorview, it will behave radically differently than snipping out a 4x4x4 block.

The color type is first `colorview(RGB, img)` rather than last because it's a lot like `reinterpret(T, A)` or `convert(T, A)`. https://docs.julialang.org/en/latest/manual/style-guide/#Write-functions-with-argument-ordering-similar-to-Julia-Base-1

You can always make a 1-arg function like this:
```julia
img = load("mandrill") |> channelview |> modifyelements |> A->colorview(RGB, A)
```

**Comment by johnnychen94** [comment]
Similar to https://github.com/zygmuntszpak/ImageBinarization.jl/issues/68, we could introduce a curried form of `colorview` so that `colorview(T)` returns a function.

This makes the pipeline nicer 😄 

```
img = load("mandrill") |> channelview |> modifyelements |> colorview(RGB)
```

Though, there seems to be some discussion and inconsistency of "what function should have curried form?": https://github.com/JuliaLang/julia/issues/33193
