### ISSUE TITLE
Performance degraded with AxisArrays

### ISSUE THREAD

**Issue by Cody-G** [JuliaImages/ImageCore.jl#28]
The second `red` call below takes 15 times longer than the first.  `code_warntype` shows that inference is failing (lots of `Box` types).  Is this JuliaLang/julia#15276?

The issue doesn't come up any time I'm indexing an image base on an `AxisArray`. I've only noticed it with colored views of images, but I didn't explore thoroughly.

```
imgc1 = colorview(RGB, zeros(500,500,60), zeroarray, zeroarray)
imgc2 = colorview(RGB, AxisArray(zeros(500,500,60)), zeroarray, zeroarray)

@time red(imgc1)
@time red(imgc2)

```

**Comment by timholy** [comment]
How is `red` defined? I get this:
```julia
julia> red(imgc1)
ERROR: MethodError: no method matching red(::ImageCore.ColorView{ColorTypes.RGB{Float64},3,ImageCore.StackedView{Float64,4,Tuple{Array{Float64,3},ImageCore.ZeroArray{Float64,3,Base.OneTo{Int64}},ImageCore.ZeroArray{Float64,3,Base.OneTo{Int64}}}}})
Closest candidates are:
  red(::ColorTypes.ARGB32) at /home/tim/.julia/v0.5/ColorTypes/src/traits.jl:17
  red(::ColorTypes.RGB24) at /home/tim/.julia/v0.5/ColorTypes/src/traits.jl:16
  red(::ColorTypes.AbstractRGB{T}) at /home/tim/.julia/v0.5/ColorTypes/src/traits.jl:14
  ...
```
I can use `red.(img)` to work elementwise over the arrays, but I get similar performance in both cases:
```julia
julia> @time red.(imgc1);
  0.158210 seconds (33 allocations: 114.442 MB, 9.51% gc time)

julia> @time red.(imgc2);
  0.125957 seconds (54 allocations: 114.443 MB, 6.42% gc time)
```

**Comment by Cody-G** [comment]
That's interesting...red is defined in `Images` for me:

```
@which red(imgc)
red{CV<:ColorTypes.Color{T,N}}(img::AbstractArray{CV,N<:Any}) at /home/cody/.julia/v0.5/Images/src/algorithms.jl:148
```

By the way, is there a way to get  a view of a specific color channel (say, red)?  I can do it by calling `channelview` and then calling `Base.view` on the result, but I'm wondering if I'm missing a way to ask for a red view directly.

**Comment by timholy** [comment]
Hah, I had just said `using ImageCore`. I had forgotten that these were defined in Images. We should probably deprecate them...notice they are several times slower than the broadcast version.

~~It's definitely not JuliaLang/julia#15276 because `@time` doesn't show massive numbers of allocations.~~ (EDIT: I was looking at the wrong version, there are allocations, not quite sure why. GC frame?)

Profiling showed something interesting (I'm just snipping out a small portion):
```
        7307 ./abstractarray.jl:805; _getindex
         7296 ./abstractarray.jl:292; checkbounds
          7290 ./abstractarray.jl:278; checkbounds
           6    ./abstractarray.jl:331; checkbounds_indices
           7284 /home/tim/.julia/v0.5/ImageCore/src/colorchannels.jl:165; indices
            7281 /home/tim/.julia/v0.5/ImageCore/src/colorchannels.jl:358; colorview_indices
             4  /home/tim/.julia/v0.5/AxisArrays/src/core.jl:0; indices(::AxisArrays.AxisArray{Float64,3,Array{Float64,3},Tuple{AxisArrays.Axis{:row,Base.On...
             17 /home/tim/.julia/v0.5/AxisArrays/src/core.jl:244; indices(::AxisArrays.AxisArray{Float64,3,Array{Float64,3},Tuple{AxisArrays.Axis{:row,Base.On...
```
A useful tip is that if a function call is `@inline`d, then the types of the arguments aren't printed in the profile trace. (ProConsequently, you can see that `indices` is failing to inline for an `AxisArray`. I just added `@inline` in front of that line and got this:
```julia
julia> @time red(imgc2);
  0.451865 seconds (7 allocations: 114.441 MB, 1.38% gc time)
```
which is almost 30x faster than what I was getting before that.

Thanks for the report! I'll submit a PR to AxisArrays.

> By the way, is there a way to get a view of a specific color channel (say, red)? I can do it by calling channelview and then calling Base.view on the result, but I'm wondering if I'm missing a way to ask for a red view directly.

No, there isn't. It's an interesting idea, might be worth adding. One could use `channelview(img, :red)`, but in cases like this one here where `img` is a `ColorView{StackedView{...}}` you *could* have type information but won't get it. `channelview(img, Val{:red})`? We could alternatively have `redview`, but somehow that seems ugly.

**Comment by Cody-G** [comment]
The `@inline` profiling tip is much appreciated! Also thanks for submitting the fix!

Yes I am getting a lot of extra allocations.  I'm not sure how to tell whether it's a GC frame issue or not...

I agree that `redview` is ugly, especially if we wanted to support all color encodings (HSV etc).  `channelview(img, Val{:red})` seems like a good syntax.  I'm not sure I understand how the implementation would go...what mechanism would allow it to generalize to any color channel in any encoding?

**Comment by timholy** [comment]
Perhaps if one wrote it as `channelview(img, Val{:r})` it would be generalizable, the difference being that the symbol is also the name of the field that you'd want to extract.

But if you don't need to set values (i.e., you want read-only access), there's an easier answer (one that works today): `v = mappedarray(red, img)`.

**Comment by Cody-G** [comment]
I like the elegance of `mappedarray(red, img)` but in the GUI tool that I made recently I set values of color channels as the user paints the image.  So it wouldn't work in that case.  For now I think I can stick with using `channelview` followed by `view`. I'll try to implement `channelview(img, Val{:r})` when I get more time.

**Comment by timholy** [comment]
The performance issue was fixed by https://github.com/JuliaArrays/AxisArrays.jl/commit/ae9ccb0f5ca981e57f698c3af2420fe3a4da61bd
