### ISSUE TITLE
How do we interpret AbstractArray{<:Number, N} where N >= 3

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/ImageCore.jl#77]
For `img::AbstractArray{<:Number, 2}` we can interpret it as `Gray2dImage`, but things become different when it comes to `ndims(img) >= 3`, it can be `Gray3dImage`, but most of the time(at least in other languages) it is a channelview of `Color3` images, and sometimes `RGB` by default.

In last PR #76, I introduced
```julia
const const GrayLike{T<:Union{Bool, FixedPoint, AbstractFloat}} = Union{T,AbstractGray{T}}
const GenericGrayImage{N, T<: GrayLike} = AbstractArray{<:GrayLike{T}, N}
const Gray2dImage{T<: GrayLike, N} = Generic2dImage{2, T}
```

It's okay with `Gray2dImage`, but it would introduce problems with `GenericGrayImage`, unless we say "by default we treat 3d number array as Gray3dImage". Can we say so?

**Comment by timholy** [comment]
Yes: https://juliaimages.org/latest/quickstart/#Array-elements-are-pixels-(and-vice-versa)-1. Old versions of JuliaImages tried to do all kinds of hacky things to guess user intent, but with the 0.6 release of Images.jl we decided to make "one array element = one pixel" one of the core abstractions of the entire JuliaImages suite. Having color types like `RGB` makes "meaning" completely unambiguous, just like annotating axes as `Axis{:time}` makes it completely unambiguous that one has a time dimension in the array.

The reason Python & Matlab bake in these hacky assumptions about dimensionality is because they don't have any viable alternative; without killing performance, they simply cannot provide the types that Julia allows. We shouldn't compromise our own design to imitate languages that are constrained by their limiitations. For people who do 3d & 4d image processing (me, @juliohm, maybe others), this is really crucial. Even "1d" images can be useful: in my lab's internal code, I have hundreds of tests for "images" that are 1d space + 1 time axis, simply because such arrays are easier to create and can sometimes test core principles of algorithms more quickly than higher-dimensional arrays which require bigger data sets. Unlike any of the other frameworks I know of, Julia makes it easy to write arbitrary-dimensional code, and that proves to be extremely useful in practice.

Now, these fancy types can introduce difficulties: in the early days there were all sorts of missing functionality, and you'd frequently get MethodErrors. Over time I hope most of that has been ironed out, as the types used by JuliaImages have matured. But we may still be missing some functionality, in which case I'd rather work on that. For example, if you find yourself turning to color separations repeatedly, it suggests there's something missing in our API.

If you really, really need JuliaImages to do "smart" things for color channels, annotate them so: https://github.com/JuliaImages/ImageAxes.jl/blob/d558af3f7d728eff96943891aa9f0d4fb4793991/test/runtests.jl#L101-L110. You can even dispatch on such axes as needed. But I'd really like to avoid having all kinds of `Axis{:color}`-specific implementations of methods and just encourage people to use types that make this unnecessary.

**Comment by johnnychen94** [comment]
The following pattern exists in many cases:

```julia
foo(img::GenericImage) = foo(eltype(img), img)
foo(img::AbstractArray{<:Number}) = foo(Gray(eltype(img)), img)

function foo(::Type{T}, img) where T
    out = zeros(T, size(img))
    ...
end
```

Although `Number` is interpreted as `Gray`, I'm not sure whether we need to support `Number` as an explicit type for functions strongly related to images. That is, which version of the following should we use?

```julia
function foo(::Type{T}, img) where T
    out = zeros(T, size(img))
    ...
end
```

or 

```julia
function foo(::Type{CT}, img) where CT <: Colorant
    out = zeros(CT, size(img))
    ...
end
```

Since `foo(Float32, img)` outputs `Array{Float32}`, any function that uses this output needs to support both `Array{<:Number}` and `Array{<:Colorant}`. This requirement sometimes forces me to take care of the element type when I'm trying to write high-level algorithms.

**Comment by timholy** [comment]
> The following pattern exists in many cases:

Can you provide a couple of examples? I think most of the algorithms that I've written just use plain `Number` automatically if that's the eltype. For example, `methods(restrict)`, `methods(imfilter)`, do not exhibit this pattern. Indeed, from a quick scan of the output of
```julia
julia> for nm in names(Images)
           f = getfield(Images, nm)
           if isa(f, Function)
               @show methods(f)
               println()
           end
       end
```
I am struggling to find examples of this pattern.

**Comment by johnnychen94** [comment]
For example, `binarize` in `ImageBinarization.jl`

```julia
binarize!(out::GenericGrayImage,
          img,
          f::AbstractImageBinarizationAlgorithm,
          args...; kwargs...) =
    f(out, img, args...; kwargs...)

# in-place binarize! only supports gray image input
function binarize!(img::GenericGrayImage,
                   f::AbstractImageBinarizationAlgorithm,
                   args...; kwargs...)
    tmp = copy(img)
    f(img, tmp, args...; kwargs...)
    return img
end

function binarize(::Type{T},
                  img,
                  f::AbstractImageBinarizationAlgorithm,
                  args...; kwargs...) where T
    out = Array{T}(undef, size(img))
    binarize!(out, img, f, args...; kwargs...)
    return out
end

binarize(img::AbstractArray{T},
         f::AbstractImageBinarizationAlgorithm,
         args...; kwargs...) where T <:Union{Number, Colorant} =
    binarize(Gray{eltype(T)}, img, f, args...; kwargs...)
```

https://github.com/zygmuntszpak/ImageBinarization.jl/blob/baa797713364592e22dd44d3e4952175db34cd69/src/BinarizationAPI/binarize.jl#L62-L69

**Comment by johnnychen94** [comment]
And `imfilter` does have this pattern, only that `imfilter` and `restrict` choose to not promote `Number` to `Gray{<:Number}`

```julia
function imfilter(img::AbstractArray, kernel, args...)
    imfilter(filter_type(img, kernel), img, kernel, args...)
end

function imfilter(::Type{T}, img::AbstractArray, kernel::Union{ArrayLike,Laplacian}, args...) where T
    imfilter(T, img, factorkernel(kernel), args...)
end
```

A related question is: Suppose there's a function `out_img = f(in_img)`, can we assume `eltype(out_img) == eltype(in_img)` by default? #82

**Comment by timholy** [comment]
> choose to not promote Number to Gray{<:Number}

I guess that's part of the point to me. I think most code shouldn't do this. And when it doesn't, it doesn't raise the dispatch issue you comment on above. That doesn't mean there aren't "interesting" dispatch issues, but `imfilter` does not implement much of anything differently for `Colorant` vs non-`Colorant` inputs so I don't think it's really an example of the dispatch issue you raised above.

> A related question is: Suppose there's a function out_img = f(in_img), can we assume eltype(out_img) == eltype(in_img) by default? #82

Definitely not. The key principle is to do the "natural" computation for a single output pixel and see what you get.

```julia
julia> using ImageFiltering

julia> imfilter([1, 1, 1], centered([1]))
3-element Array{Int64,1}:
 1
 1
 1

julia> imfilter([1, 1, 1], centered([1.0f0]))
3-element Array{Float32,1}:
 1.0
 1.0
 1.0

julia> imfilter([1, 1, 1], centered([1.0]))
3-element Array{Float64,1}:
 1.0
 1.0
 1.0
```

**Comment by johnnychen94** [comment]
It makes sense; this isn't a big issue since in most cases it's not too difficult to add a specialization method for `Number`.

BTW, to avoid misunderstanding, does ”I think most code shouldn't do this“ mean "most codes should not promote `Number` to `Gray{<:Number}`"?

**Comment by timholy** [comment]
> BTW, to avoid misunderstanding, does ”I think most code shouldn't do this“ mean "most codes should not promote Number to Gray{<:Number}"?

Exactly, thanks for checking!

**Comment by timholy** [comment]
I don't think there's anything that needs doing here? (Reopen if I'm wrong.)
