### ISSUE TITLE
cat Arrays without promotion?

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/ImageCore.jl#79]
Currently, when we create an array of images with mixed colors, type promotion will be used.

```julia
julia> [Gray(0.5) RGB(1.0, 0.0, 0.0)] |> typeof
Array{RGB{Float64},2}
```

Which is caused by [Colors](https://github.com/JuliaGraphics/Colors.jl/blob/835d4454e36b34fcec4bd5255779202ca2b5a358/src/conversions.jl#L173-L176) (If I understand it right)
```julia
function cnvt(::Type{CV}, c::AbstractGray) where CV<:AbstractRGB
    g = convert(eltype(CV), gray(c))
    CV(g, g, g)
end
```

Issues will come up when we try to load a batch of image files, which is often stored as `Array{Array}`.  It would be a surprise that image types are changed (e.g., Gray -> RGB), regardless of the unwanted memory allocation.

Should we deprecate `Color1->Color3` conversion, or should we change the behavior of `cat`?

--- update

Got bitten by the following behavior, looks like the first line works as expected, while the second is quite a suprise (although sometimes it's quite handy)
```julia
[load(f) for f in ["gray.png", "color.png"]] |> typeof # Array{Array{T,2} where T,1}
[load("gray.png"), load("color.png")] |> typeof # Array{Array{RGB{Normed{UInt8,8}},2},1}
```

**Comment by timholy** [comment]
This is standard Julia behavior, e.g.,

```julia
julia> [1; 1.0]
2-element Array{Float64,1}:
 1.0
 1.0
```
This is useful because Julia's performance is best when it can infer types, thus it's best to build containers with concrete eltype. Of course, not all objects can be converted to a common concrete type:
```julia
julia> [3, "hello"]
2-element Array{Any,1}:
 3       
  "hello"
```

When you *don't* want this behavior, you can specify the eltype directly:
```julia
julia> Real[1; 1.0]
2-element Array{Real,1}:
 1  
 1.0
```

An analog here could be
```julia
julia> Colorant[Gray(0.5) RGB(1.0, 0.0, 0.0)]
1×2 Array{Colorant{Any},2} with eltype Colorant:
 Gray{Float64}(0.5)  RGB{Float64}(1.0,0.0,0.0)
```

The difference between your two `load` constructs is presumably due to the fact that the first invokes a generator, which means that the eltype is computed by inference, and the `load` is obviously non-inferrable. (I'm actually surprised the eltype of the first isn't `Any`.)

**Comment by johnnychen94** [comment]
That's a very clear elaboration, thanks!

I'll keep this issue open until I find time to add this `Gray -> RGB` behavior in the FAQs page of https://juliaimages.org/latest/ (which not exists at present)

**Comment by johnnychen94** [comment]
close this issue in favor of https://github.com/JuliaImages/juliaimages.github.io/issues/108
